server:
  port: 8081

spring:
  profiles:
    active: dev
  datasource:
    #com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sso?seUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: a
    platform: mysql
    name: sso
